"""Added one more status and event type general

Revision ID: 34fd6898b729
Revises: aa8b819fdada
Create Date: 2026-05-15 10:45:57.440144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34fd6898b729'
down_revision = 'aa8b819fdada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT") 
    op.execute("ALTER TYPE submissionstatus ADD VALUE 'QUEUED'")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
