"""add human review table

Revision ID: 45512ed30ca5
Revises: 34fd6898b729
Create Date: 2026-05-19 10:27:19.182680

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45512ed30ca5'
down_revision = '34fd6898b729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humanreview',
    sa.Column('submission_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('reviewer_comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_verdict', sa.Enum('PENDING', 'PASSED', 'FAILED', name='humanreviewstatus'), nullable=False),
    sa.Column('evaluator_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humanreview_submission_id'), 'humanreview', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_humanreview_submission_id'), table_name='humanreview')
    op.drop_table('humanreview')
    # ### end Alembic commands ###
