"""add attachment_object_name to submission

Revision ID: 56621201a404
Revises: 5c17998686ed
Create Date: 2026-05-14 18:36:45.953883

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56621201a404'
down_revision = '5c17998686ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment', 'problem_statement',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('submission', sa.Column('attachment_object_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    op.drop_column('submission', 'attachment_object_name')
    op.alter_column('assessment', 'problem_statement',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
