"""add human review table

Revision ID: a9f02beb0ecf
Revises: 2e006099b324
Create Date: 2026-05-15 09:47:13.530111

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9f02beb0ecf'
down_revision = '2e006099b324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humanreview',
    sa.Column('submission_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('provisional_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer_comments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_verdict', sa.Enum('PENDING', 'PASSED', 'FAILED', name='humanreviewstatus'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humanreview_assessment_id'), 'humanreview', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_humanreview_submission_id'), 'humanreview', ['submission_id'], unique=False)
    op.alter_column('assessment', 'problem_statement',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    op.alter_column('assessment', 'problem_statement',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_humanreview_submission_id'), table_name='humanreview')
    op.drop_index(op.f('ix_humanreview_assessment_id'), table_name='humanreview')
    op.drop_table('humanreview')
    # ### end Alembic commands ###
