"""Added one more status and event type

Revision ID: aa8b819fdada
Revises: 38da6febf349
Create Date: 2026-05-15 10:41:57.078165

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aa8b819fdada'
down_revision = '38da6febf349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
